"""
Django settings for netology_pd_diplom project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os, sys, sentry_sdk
from dotenv import load_dotenv
load_dotenv()
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'backend',
    'bootstrap4',
    'drf_spectacular',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'backend.middleware.SentryUserContextMiddleware',
]

ROOT_URLCONF = 'netology_pd_diplom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'netology_pd_diplom.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }


}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Бекенды аутентификации в различных соцсетях
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',     # Google
    'social_core.backends.github.GithubOAuth2',     # GitHub
    'social_core.backends.vk.VKOAuth2',             # VK
    'django.contrib.auth.backends.ModelBackend',    # Стандартная аутентификация
)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AUTH_USER_MODEL = 'backend.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp.mail.ru'

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_PORT = '465'
EMAIL_USE_SSL = True
SERVER_EMAIL = EMAIL_HOST_USER

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 40,

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',

    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework.authentication.TokenAuthentication',
    ),

    # Настройка DRF
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    # Настройки throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # для неавторизованных
        'rest_framework.throttling.UserRateThrottle',   # для авторизованных
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',      # неавторизованные: 100 запросов в день
        'user': '1000/day',     # авторизованные: 1000 запросов в день
        'register': '5/hour',   # регистрация: 5 раз в час
        'login': '10/hour',     # авторизация: 10 раз в час
        'export': '20/hour',    # экспорт: 20 раз в час
        'import': '5/hour',     # импорт: 5 раз в час
        'basket': '200/hour',   # корзина: 200 раз в час
        'order': '50/hour',     # заказы: 50 раз в час
    },

}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Для Redis
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 10 * 60  # 10 минут
CELERY_BEAT_SCHEDULE = {
    'cleanup-old-exports': {
        'task': 'backend.tasks.cleanup_old_exports',
        'schedule': 86400.0,  # раз в сутки (в секундах)
    },
}

# Базовый URL для ссылок в письмах
BASE_URL = 'http://localhost:8000'

# Настройки для хранения файлов экспорта
EXPORT_FILES_ROOT = os.path.join(BASE_DIR, 'export_files')
os.makedirs(EXPORT_FILES_ROOT, exist_ok=True)


# Настройка темы админки
ADMIN_INTERFACE = {
    'title': 'Магазин Электроники',
    'logo': 'logo.png',  # положите логотип в static/
    'favicon': 'favicon.ico',
    'theme': 'default',  # или 'dark', 'primary'
}

# Настройки для DRF-Spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Интернет-магазин API',
    'DESCRIPTION': 'API для интернет-магазина электроники. Поддерживает управление заказами, товарами, корзиной и аутентификацию.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'SECURITY': [
        {'tokenAuth': []},
    ],
    'SECURITY_SCHEMES': {
        'tokenAuth': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
            'description': 'Token-авторизация. Формат: Token <ваш_токен>',
        },
    },
}

# Для тестов запуска используем локальный кэш
if 'test' in sys.argv:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Настройки социальных сетей:
# URL для перенаправления после успешной авторизации
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/api/v1/user/login'

# Настройки для провайдеров (замените на свои ключи после регистрации приложений)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']

SOCIAL_AUTH_GITHUB_KEY = os.getenv('SOCIAL_AUTH_GITHUB_KEY', '')
SOCIAL_AUTH_GITHUB_SECRET = os.getenv('SOCIAL_AUTH_GITHUB_SECRET', '')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

# Настройки для создания пользователей из соцсетей
SOCIAL_AUTH_USER_MODEL = 'backend.User'
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True  # Использовать email как username
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Настройки для загрузки файлов
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Настройки для SENTRY
SENTRY_DSN = os.getenv('SENTRY_DSN', '')

if SENTRY_DSN:
    # Проверяем, не инициализирован ли уже SDK
    if not sentry_sdk.get_client().is_active():
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.5 if not DEBUG else 1.0,
            send_default_pii=True,
            environment=os.getenv('SENTRY_ENVIRONMENT', 'development'),
            release='1.0.0',
            debug=DEBUG,  # Включаем debug только при DEBUG=True
        )

        if DEBUG:
            sentry_sdk.capture_message("Sentry инициализирован в режиме DEBUG", level="info")
    else:
        print("[Sentry] SDK already initialized, skipping...")